### PR TITLE
changed nav and bg

### PR DESCRIPTION
**Pull request by naijwu**
### TL;DR:
Made the page match more closely to Figma

### Changes:
- navbar code structure (for easier mobile media query modifications) - didn't touch components though
- navbar (css)
- button styling (css)
- NFT card bg styling (css)
- added gradient background (css)

### CODE REVIEW

**Comment by straightupjac** [comment]
Screen Shot 2021-12-20 at 7 34 39 PM
about page is not rendering correctly for me

**Comment by straightupjac** [comment]
Screen Shot 2021-12-20 at 7 36 00 PM
also cramped on mobile

**Comment by straightupjac** [comment]
Thanks so much for doing this though! love this change -- just some visual issues

**Comment by straightupjac** [comment]
thanks @naijwu for the changes! could you fix the merge conflict and run yarn build locally -- its what vercel runs to deploy and needs to work before we can merge!

**Review by bjmoonn — APPROVED** [review]

**Pull request merged**
